# Generated by Django 3.2.9 on 2021-11-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docstore', '0002_auto_20211113_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='folder',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
